apiVersion: 1

datasources:
  - name: InfluxDB_V2
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: homebrew
      defaultBucket: fermentation
      tlsSkipVerify: true
    secureJsonData:
      token: "my-super-secret-token" # Must match .env token!